name: "[cron] automation"

on:
  schedule: # UTC
    - cron: '*/5 * * * *'

jobs:
  run-script:
    name    : run script
    runs-on : ubuntu-latest
    steps   :
      - name  : Checkout repository
        uses  : actions/checkout@v2

      - name  : Setup Python
        uses  : actions/setup-python@v2
        with  :
          python-version : '2.7.18'
          architecture   : 'x64'

      - name  : Run Python
        # working-directory : scripts/python
        run   : |
          echo "123"
          cd scripts/python
          ls -l
          python -V
          # pip install -r requirements.txt
          # python main.py

