name: "[cron] automation"

on:
  schedule: # UTC
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    name    : run script
    runs-on : ubuntu-latest
    timeout-minutes : 60
    steps   :
      - name  : Checkout repository
        uses  : actions/checkout@v2

      - name  : Setup Python
        uses  : actions/setup-python@v2
        with  :
          python-version : '2.7.18'
          architecture   : 'x64'

      - name  : Run Python
        id    : step-python
        # working-directory : scripts/python
        run   : |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

          cd scripts/python
          ls -l
          python -V
          pip install -r requirements.txt
          python src/main.py

          git add -N . # 新規ファイルを含める
          git_diff_count=`git diff --name-only | wc -l`
          echo "git_diff_count: ${git_diff_count}"
          echo "::set-output name=git-diff-count::${git_diff_count}"

      - name  : Git settings
        run   : |
          git config --local user.name  github-actions
          git config --local user.email github-actions@github.com

      - name  : Create new branch/pr
        env   :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run   : |
          echo ${{ steps.step-python.outputs.git-diff-count }}
          release_branch="release/auto_${{ env.CURRENT_DATETIME }}"
          git switch -c      ${release_branch}
          git push -u origin ${release_branch}
          echo `git branch --contains`

          git add .
          git commit -m "auto updated."
          git push

          hub pull-request --base main --head ${release_branch} -m "[release] ${{ env.CURRENT_DATETIME }}"

