name: "[PR] auto merge"

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  main:
    name    : run main
    runs-on : ubuntu-latest
    if      : startsWith(github.head_ref, 'actions/cron_auto-pr_')
    timeout-minutes : 60
    steps   :

      - name  : Checkout repository
        uses  : actions/checkout@v2

      - name  : Setup Config
        env   :
          TZ    : 'Asia/Tokyo'
        run   : |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
          git config --local user.name  github-actions
          git config --local user.email github-actions@github.com

      - name  : Merge New PR
        env   :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER   : ${{ github.repository_owner }}
          REPO_NAME    : ${{ github.event.repository.name }}
        run   : |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo ${PR_NUMBER}
          PR_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/pull/${PR_NUMBER}"
          echo ${PR_URL}

          hub merge ${PR_URL}
